//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestGit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config
    {
        public int id { get; set; }
        public string max_renewal { get; set; }
        public string sys_name { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public string website { get; set; }
    }
}
