//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestGit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback_comments
    {
        public int id { get; set; }
        public int reservation { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
    }
}
