//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestGit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int id { get; set; }
        public string title { get; set; }
        public string barcode { get; set; }
        public string description { get; set; }
        public Nullable<byte> available { get; set; }
        public Nullable<int> library { get; set; }
        public string image { get; set; }
        public Nullable<int> category { get; set; }
        public string author { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<System.DateTime> publishing_date { get; set; }
        public string edition { get; set; }
    }
}
