//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestGit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.loans = new HashSet<loan>();
            this.reservation_items = new HashSet<reservation_items>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string barcode { get; set; }
        public string description { get; set; }
        public Nullable<byte> available { get; set; }
        public Nullable<int> library { get; set; }
        public string image { get; set; }
        public Nullable<int> category { get; set; }
        public string author { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<System.DateTime> publishing_date { get; set; }
        public string edition { get; set; }
    
        public virtual category category1 { get; set; }
        public virtual library library1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loan> loans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation_items> reservation_items { get; set; }
    }
}
