//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestGit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public int id { get; set; }
        public int reservation { get; set; }
        public int item { get; set; }
        public System.DateTime loandate { get; set; }
        public System.DateTime duedate { get; set; }
        public byte renewal { get; set; }
        public byte checked_in { get; set; }
    
        public virtual item item1 { get; set; }
        public virtual reservation reservation1 { get; set; }
    }
}
