//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestGit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public int user { get; set; }
        public System.DateTime dateRevesed { get; set; }
        public Nullable<int> pickuplocation { get; set; }
        public Nullable<System.DateTime> until { get; set; }
        public byte canceled { get; set; }
    }
}
